theme: jekyll-theme-tactile
show_downloads: False
description: [I'm a M.S. student in **Machine Learning** at University of California, San Diego. This is a portfolio of my projects in data science and deep learning.]
